# Generated by Django 5.1 on 2025-12-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_bottomstyle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=250)),
                ('image', models.ImageField(upload_to='category_cards/')),
                ('link', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'category_cards',
                'ordering': ['order'],
            },
        ),
    ]
