# Generated by Django 5.1 on 2025-12-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_banner_description_banner_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensHoodieGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('position', models.IntegerField(choices=[(1, 'Main Banner (Large - Top)'), (2, 'Card 2 (Bottom Left)'), (3, 'Card 3 (Bottom Center-Left)'), (4, 'Card 4 (Bottom Center-Right)'), (5, 'Card 5 (Wide - Bottom Right)')], unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Men's Hoodie Grid Item",
                'verbose_name_plural': "Men's Hoodie Grid Items",
                'db_table': 'mens_hoodie_grid',
                'ordering': ['position'],
            },
        ),
    ]
