# Generated by Django 5.1 on 2025-12-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_menshoodiegrid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycard',
            name='image',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
