# Generated by Django 5.1 on 2025-12-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_change_categorycard_image_to_urlfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycard',
            name='background_color',
            field=models.CharField(blank=True, default='#1a1a1a', max_length=7),
        ),
    ]
