# Generated by Django 5.1 on 2025-12-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_add_background_color_to_categorycard'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='background_color',
            field=models.CharField(blank=True, default='#f5ebe0', max_length=7),
        ),
    ]
