# Generated by Django 5.1 on 2025-12-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_add_background_color_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
