# Generated by Django 5.1 on 2025-12-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_add_category_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottomstyle',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bottomstyle',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bottomstyle',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('hoodies', 'Hoodies'), ('tshirts', 'T-Shirts'), ('shirts', 'Shirts'), ('pants', 'Pants'), ('bottomwear', 'Bottom Wear'), ('accessories', 'Accessories'), ('shoes', 'Shoes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sizetemplate',
            name='category_type',
            field=models.CharField(choices=[('hoodies', 'Hoodies'), ('tshirts', 'T-Shirts'), ('shirts', 'Shirts'), ('pants', 'Pants'), ('bottomwear', 'Bottom Wear'), ('accessories', 'Accessories'), ('shoes', 'Shoes')], max_length=20, unique=True),
        ),
    ]
