# Generated by Django 5.1 on 2025-12-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_update_bottomstyle_for_cloudinary'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottomstyle',
            name='background_color',
            field=models.CharField(blank=True, default='#f5ebe0', max_length=7),
        ),
    ]
