# Generated by Django 5.1 on 2025-12-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_add_background_color_to_bottomstyle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottomstyle',
            name='background_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=7),
        ),
    ]
