# Generated by Django 5.1 on 2025-12-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_update_bottomstyle_default_bgcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='JacketsGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=250)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('background_color', models.CharField(blank=True, default='#ffffff', max_length=7)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('position', models.IntegerField(choices=[(1, 'Large Left Card (2 rows)'), (2, 'Top Right Card 1'), (3, 'Top Right Card 2'), (4, 'Bottom Left Card'), (5, 'Bottom Center Card'), (6, 'Bottom Right Large Card')], unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jackets Grid Item',
                'verbose_name_plural': 'Jackets Grid Items',
                'db_table': 'jackets_grid',
                'ordering': ['position'],
            },
        ),
    ]
