# Generated by Django 5.1 on 2025-12-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_jackets_grid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('discount_text', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('button_link', models.CharField(default='/shop', max_length=255)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('background_color', models.CharField(blank=True, default='#f8f8f8', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promotional Banner',
                'verbose_name_plural': 'Promotional Banners',
                'db_table': 'promotional_banners',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='jacketsgrid',
            name='position',
            field=models.IntegerField(choices=[(1, 'Large Left Card (Full Height)'), (2, 'Top Middle Card'), (3, 'Top Right Card'), (4, 'Bottom Middle Card'), (5, 'Bottom Right Card')], unique=True),
        ),
    ]
