# Generated by Django 5.1 on 2026-01-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_shoesgrid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoesCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=250)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('link', models.CharField(blank=True, default='/shop?category=shoes', max_length=255)),
                ('background_color', models.CharField(blank=True, default='#ffffff', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shoes Card',
                'verbose_name_plural': 'Shoes Cards',
                'db_table': 'shoes_cards',
                'ordering': ['order'],
            },
        ),
    ]
