# Generated by Django 5.1 on 2026-01-19 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_shoescard'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, help_text='Order position (lower = higher priority)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='The main product', on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='products.product')),
                ('related', models.ForeignKey(help_text='The related product to recommend', on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='products.product')),
            ],
            options={
                'verbose_name': 'Related Product',
                'verbose_name_plural': 'Related Products',
                'db_table': 'related_products',
                'ordering': ['position', '-created_at'],
                'indexes': [models.Index(fields=['product', 'is_active'], name='related_pro_product_7aee0b_idx')],
                'unique_together': {('product', 'related')},
            },
        ),
    ]
